### ISSUE TITLE
Three undefined names

### ISSUE THREAD

**Issue by cclauss** [abingham/traad#100]
__cmp()__ is present in Python 2 but was removed in Python 3.

flake8 testing of https://github.com/abingham/traad on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./distribute_setup.py:476:20: F821 undefined name 'cmp'
            return cmp(dir1.name, dir2.name)
                   ^
./traad/app.py:325:12: F821 undefined name 'request'
    args = request.json
           ^
./traad/app.py:330:20: F821 undefined name 'context'
        'results': context.workspace.get_definition_location(
                   ^
3     F821 undefined name 'cmp'
3
```

**Comment by abingham** [comment]
The first one is protected by a version check. The other two should be fixed as of dd766c7adb663866f229fe4b45ee4391da2128b3. Thanks!
