### ISSUE TITLE
Investigate code-completion performance on larger projects

### ISSUE THREAD

**Issue by abingham** [abingham/traad#20]
It seems that performance on larger projects (e.g. ipython) is not as good as it needs to be. There are reports of noticeable lag when typing. So, we need to look into that, see what might be done, etc. It could be that rope is the slow-down.

**Comment by mcepl** [comment]
There is some work on the topic of rope profiling and related in https://github.com/python-rope/rope/issues/44 Of course, merge requests welcome! :)
