### ISSUE TITLE
Connecting to traad server seems broken in emacs

### ISSUE THREAD

**Issue by PythonNut** [abingham/traad#76]
I just took this for a spin again in `emacs24.5 -Q`, and I can't seem to get the client to connect to the `traad` server. When I attempt, I get the following error:

    REQUEST [error] Error (error) while connecting to http://127.0.0.1:40641/refac\tor/rename.

I have run `traad-install-server`, and everything appeared to run fine.

**Comment by abingham** [comment]
Sorry, I just saw this! I'm hoping to have some time to look at traad issues in the near future.

**Comment by abingham** [comment]
Can you should me the contents of your `*traad-server*` buffer when this problem happens?

And is this happening with Python 3?

**Comment by PythonNut** [comment]
Hey, sorry. I should be able to get back to you soon. Maybe tomorrow.

**Comment by PythonNut** [comment]
1. This is indeed `python3.5`
2. I can no longer seem to reproduce this issue.

I'll close this and start a new issue for the problems I do see.
