### ISSUE TITLE
RuntimeError: Request context not initialized [python 3]

### ISSUE THREAD

**Issue by mfouesneau** [abingham/traad#83]
Since using python 3 I am now getting many of these 
```RuntimeError: Request context not initialized [python 3]```

I cannot find a common source. It seems some variables are not defined.
(I tried the latest version from the repository, same issues)

**Comment by abingham** [comment]
Can you give me some steps to reproduce this? Or at least some context for when the error is occurring?

**Comment by mfouesneau** [comment]
I can't, I don't know what happens. Click on a link would be the procedure.
Not all pages throw errors. Strangely is not linked to the page content itself.

**Comment by abingham** [comment]
Do you mean links in emacs or something? traad by itself doesn't really
have any "links" for clicking that I can think of.

**Comment by mfouesneau** [comment]
I generate a website, and some links to other pages now throw this context error.
It was working before.

**Comment by mfouesneau** [comment]
Oh I am sorry somehow I am not in the correct repo. Nothing to do with Traad.

issue closed

**Comment by rajeevhcu** [comment]
do you find solution of this issue?
