### ISSUE TITLE
Support for inlining of variables

### ISSUE THREAD

**Issue by talwrii** [abingham/traad#90]
This comes up more than one imagines. I have hit this as part of refactoring.

Example:

    for x in xs:
        a = f(x)
        yield g(a)

I want to extract f and g, so I manually change this code to

    for x in xs:
        a = f(x)
        result = g(a)
        yield result

And then use extract out lines 2 and 3 to get

    for x in xs:
        result = new_method(x)
        yield result

I then need to incline result in both new_method and here.

Variable inlining is supported in rope. So I imagine it mightn't be too much work to implement.

**Comment by talwrii** [comment]
This also comes up in order to make the arguments that a function take more specific.

    c = f(a.b)
    d = g(c)

I want to turn this into a function that takes a.b as an argument (rather than a).

To cause this to happen I convert the code to the following

    input = a.b
    c = f(input)
    d = g(c)

And then extract lines 2, and 3

     input = a.b
     d = new_method(input)

At this point I want / need to inline input again.

**Comment by abingham** [comment]
This would certainly be nice have. Hopefully I'll get some time soon to work it.

**Comment by abingham** [comment]
I've added support for rope's inline refactoring in the [`added-inline` branch](https://github.com/abingham/traad/tree/added-inline). Give it a try and let me know what you think.

If you're using traad via the emacs extension, there's an [associated branch in `emacs-traad`](https://github.com/abingham/emacs-traad/tree/added-inline).

**Comment by talwrii** [comment]
That was quick, and is quite exciting. Trying this out now.

**Comment by abingham** [comment]
Let me know if it works for you. If so, I'll merge it into main.

**Comment by abingham** [comment]
@talwrii Did this work for you?

**Comment by abingham** [comment]
@talwrii I'm going to assume that this works and merge it in.
